name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # e.g., v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install module
        run: |
          pip install .

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Check build
        run: |
          twine check dist/*

      - name: Publish package distributions to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1